version: "2.4"
services:
  backend:
    build: backend
    image: mktiti/fsearch-backend
    container_name: fsearch-backend
    restart: unless-stopped
    environment:
      - BACKEND_MIN_HEAP
      - BACKEND_MAX_HEAP
      - SPRING_PROFILE
    volumes:
      - "${STORE_CACHE_PATH}:/usr/share/fsearch/store-cache/"
      - "${JCL_DOCS_PATH}:/usr/share/fsearch/docs/"
    ports:
      - "8081:8080"
  frontend:
    build: frontend-vue
    image: mktiti/fsearch-frontend
    container_name: fsearch-frontend
    restart: unless-stopped
    environment:
      - API_PATH
    ports:
      - "8082:8080"
    mem_limit: 10m
  facade:
    build: facade-docker
    image: mktiti/fsearch-facade
    container_name: fsearch-facade
    restart: unless-stopped
    volumes:
      - /data/fsearch/certbot/conf:/etc/letsencrypt
      - /data/fsearch/certbot/www:/var/www/certbot
    ports:
      - "${FACADE_PORT}:80"
      - "${FACADE_PORT_SSL}:443"
    links:
      - "backend:backend"
      - "frontend:frontend"
    mem_limit: 10m
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - /data/fsearch/certbot/conf:/etc/letsencrypt
      - /data/fsearch/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    mem_limit: 10m
