version: "3.3"
services:
  backend:
    build: backend
    container_name: fsearch-backend
    environment:
      - BACKEND_MIN_HEAP
    ports:
      - "8081:8080"
  frontend:
    build: frontend-vue
    container_name: fsearch-frontend
    ports:
      - "8082:8080"
  facade:
    build: facade-docker
    container_name: fsearch-facade
    ports:
      - "${FACADE_PORT}:8080"
    links:
      - "backend:backend"
      - "frontend:frontend"
