version: "3.3"
services:
  backend:
    build: backend
    container_name: fsearch-backend
    restart: unless-stopped
    environment:
      - BACKEND_MIN_HEAP
    volumes:
      - "${STORE_CACHE_PATH}:/usr/share/fsearch/store-cache/"
    ports:
      - "8081:8080"
  frontend:
    build: frontend-vue
    container_name: fsearch-frontend
    restart: unless-stopped
    ports:
      - "8082:8080"
  facade:
    build: facade-docker
    container_name: fsearch-facade
    restart: unless-stopped
    volumes:
      - /data/fsearch/certbot/conf:/etc/letsencrypt
      - /data/fsearch/certbot/www:/var/www/certbot
    ports:
      - "${FACADE_PORT}:80"
      - "${FACADE_PORT_SSL}:443"
    links:
      - "backend:backend"
      - "frontend:frontend"
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - /data/fsearch/certbot/conf:/etc/letsencrypt
      - /data/fsearch/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
