# Spring Config
server:
  port: ${port:8080}
  http2.enabled: true
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

api.base.path: "/"
cross.origin: "*"
jcl.javadoc.path: null

# Very rough limit for in-mem stored javadoc (MB)
cache.docs.approxlimit: 100
# Very rough limit for in-mem stored type info (MB)
cache.info.approxlimit: 100
# Very rough limit for in-mem stored artifact dependencies (MB)
cache.deps.approxlimit: 10

springdoc.api-docs.path: /${api.base.path}api-docs