# Common base of Spring configuration
# Can and should be overwritten by environment specific configs (see environments/{env}/config/backend/application.yml)

server:
  port: 8080
  http2.enabled: true
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

api.base.path: "/"
cross.origin: "*"

jcl.javadoc.path: "/usr/share/fsearch/docs/jdk-8-partial.zip"
data-store.path: "/usr/share/fsearch/store-cache/"

cache:
  # Very rough approximations for limits on in-mem caches (in MB)
  approxlimit:
    docs: 100
    info: 100
    deps: 10

springdoc.api-docs.path: /${api.base.path}api-docs